### ISSUE TITLE
Add Chromecast detection

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1168]
see ua-parser/uap-core#211 for more info.

**Comment by mimmi20** [comment]
@asgrim @jaydiablo What do you think, Is the Chromecast only the device, or is the name also used for the platform or browser?

**Comment by jaydiablo** [comment]
Just looking here: https://www.google.com/intl/en_us/chromecast/?utm_source=chromecast.com 

It seems like there are (currently) three different chromecast devices. I assume the Audio one probably doesn't have a user-agent since it doesn't seem like it does web browsing.

Unfortunately I don't have (or have access to) anything Chromecast, so I can't really test anything to see if there's a way to tell one device from the other.

A general "Chromecast" device may be nice though, as I don't suspect you'd see a non-chromecast device using the Chromecast platform (perhaps aside from development/testing emulators).
