### ISSUE TITLE
Consoles

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1271]
see serbanghita/Mobile-Detect#240 for more details.

**Comment by jaydiablo** [comment]
Happy to take a look at this one (pulling some useragents from our logs as we speak), quick question though, "playstation" appears both in "tv-device" devices and "console" devices:

https://github.com/browscap/browscap/blob/master/resources/devices/console/sony.json

https://github.com/browscap/browscap/blob/master/resources/devices/tv-device/sony.json#L41

Should these all be brought into the "Console" group?

Same for Xbox?

https://github.com/browscap/browscap/blob/master/resources/devices/tv-device/microsoft.json

**Comment by jaydiablo** [comment]
Ah, I think I see.

"Console" seems to require that the device be a mobile device.

"TV Device" requires that it isn't (from the switch statement here: https://github.com/browscap/browscap/blob/master/src/Browscap/Data/DataCollection.php#L851)

Should this remain a restriction for the "Console" type?  

If so, then I think that PS2 (https://github.com/browscap/browscap/blob/master/resources/devices/console/sony.json#L15), Playstation (https://github.com/browscap/browscap/blob/master/resources/devices/console/sony.json#L41), Wii (https://github.com/browscap/browscap/blob/master/resources/devices/console/nintendo.json#L41) and WiiU (https://github.com/browscap/browscap/blob/master/resources/devices/console/nintendo.json#L54) need to be moved to "TV Device" as they're not mobile devices.

**Comment by mimmi20** [comment]
TV devices should be all devices that are TVs or require a TV.
The WiiU should not be a TV device (I dont know if you can use it with a TV), because you can carry it with you (for eample to play in a train).
But I dont know where to take the border.

**Comment by jaydiablo** [comment]
The WiiU doesn't always require a TV (as you can play on the screen of the controller if the game can be played that way), but it does require that you're within the vicinity of the unit that is connected to the TV:

![WiiU Console](https://images.eurogamer.net/2015/articles/1/8/6/5/8/8/9/-1478009362334.jpg/EG11/resize/300x-1/quality/80/format/jpg)

You can't play the WiiU on the train, because if it gets too far away from the console, you get this:

![WiiU Communication Message](https://i.ytimg.com/vi/JbZj7ues-yk/maxresdefault.jpg)

The new Nintendo Switch, on the other hand, is both mobile and can be connected to a TV (also planning to add this device as part of this update).

So, with your logic above, I think it should be like this:

## TV Devices
 * PS2
 * Playstation
 * PS3
 * PS4
 * Xbox 360
 * Xbox One
 * Wii
 * WiiU

## Consoles
 * 3DS
 * DSi
 * New 3DS
 * Vita
 * PSP
 * Switch

**Comment by jaydiablo** [comment]
Anyone know any details about this useragent?

>Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Mobile Safari/537.36 Edge/13.10586

It appears in the test suite (https://github.com/browscap/browscap/blob/master/tests/fixtures/issues/issue-1043.php#L164), and we've actually seen it in our access logs this year (twice!).  WhichBrowser has it in their test suite as well (https://github.com/WhichBrowser/Parser/blob/master/tests/data/gaming/microsoft.yaml#L6).

I haven't found anything that demonstrates why an Xbox One would be using a useragent with a "Windows Phone" string in it.

That said, I think the way that WhichBrowser parses this one is more correct than what Browscap is doing: http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Windows+Phone+10.0%3B+Android+4.2.1%3B+Xbox%3B+Xbox+One%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F46.0.2486.0+Mobile+Safari%2F537.36+Edge%2F13.10586

Because the Xbox One doesn't run on a Windows Phone OS.

Thoughts?

**Comment by mimmi20** [comment]
Edge has its developer tools where you can change the useragent. I dont know if this combination was possible with Edge 13, in Edge 14 this is not possible by default, but can set a self defined ua.

**Comment by jaydiablo** [comment]
Here's actually another one of that variety that we've seen this year much more frequently than the other one:

>Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Mobile Safari/537.36 Edge/14.14393

In contrast to another Xbox One agent (that we've seen more than the "mobile" one above):

>Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

Same version of Chrome and Edge, I wonder if it's the Xbox One being used in some sort of mobile mode?  Perhaps it's related to the user using the Xbox App on their mobile device to control the Xbox? (http://www.digitaltrends.com/gaming/connect-smartphone-xbox-one/)

Unfortunately I don't have an Xbox One to test with.

**Comment by jaydiablo** [comment]
I ran into a similar type of agent for the Xbox 360:

>Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; Xbox)

Searching around a bit I found this site that lists a couple of useragents for the Xbox 360 and calls the second one (that has the IEMobile string in it) the "Mobile View":

http://console.maban.co.uk/device/xbox360/

I haven't been able to find much more than that though.
