### ISSUE TITLE
Edge user agent is detected as Chrome

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1318]
see ua-parser/uap-core#233 for more details.

**Comment by jaydiablo** [comment]
This gets parsed as Chrome because there is no "." after the Major Version.  The other edge agents in the test suite look like this:

>Mozilla/5.0 (Windows NT 10.0; Win64; x64; Xbox; Xbox One) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393

vs. the one from that ticket:

>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12

And the pattern is: 

`Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/* Edge/#MAJORVER#.*`

According to Microsoft, the Windows build number should always follow the Edge version: https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx

**Comment by mimmi20** [comment]
We could remove the "." from the pattern.
