### ISSUE TITLE
Add Thunderbird/45.8.0

### ISSUE THREAD

**Issue by chogsden** [browscap/browscap#1529]
Browscap v. 6023, standard
Manually, Drupal7 module browscap/browscap-php
Useragent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Thunderbird/45.8.0

**Comment by JohannesWilkeStriata** [comment]
I also see that Thunderbird running on Windows 10 is not recognized by your database. I used he latest Thunderbirtd 52.

Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Thunderbird/52.2.1 Lightning/5.4.2.1

Is there any timeline to expect it to be finished since its a half popular email client for windows also?
