### ISSUE TITLE
Opera 46 version number not identified

### ISSUE THREAD

**Issue by quackdor** [browscap/browscap#1535]
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
OPR/46.0.2597.57

**Comment by jaydiablo** [comment]
Opera 46 was added in this PR: https://github.com/browscap/browscap/pull/1435/files#diff-6d2249f8ce04df3d46f7dafb08f84ab7R3

However, there hasn't been a release of browscap since that commit was made.  Once 6024 comes out, this will be detected properly.

I've confirmed that `dev-master` parses this UA properly.

**Comment by jaydiablo** [comment]
6024 has been released and I've confirmed this parses correctly on browscap.org.

This ticket can be closed.
