### ISSUE TITLE
Tablet (BQ Aquaris M10) detected as phone!

### ISSUE THREAD

**Issue by LuisRamBar** [browscap/browscap#1572]
I implemented the lite version of Browscap and everything worked perfectly... So far.

I have discovered that the mentioned device (BQ Aquaris M10) is detected as a mobile phone, setting the variables as follows:
_device_type_ => Mobile Phone
_ismobiledevice_ => 1
_istablet_ => _null_

I tried it on an iPad and it works fine.

I don't know if it's my mistake or browscap... Can you help me?

I attach some captures.

Thanks a lot!

![image](https://user-images.githubusercontent.com/5966955/30121211-62575b2a-932b-11e7-8adc-ac0fae92e1bc.png)
![image](https://user-images.githubusercontent.com/5966955/30121262-7fe6f178-932b-11e7-9982-1b63d1f55e38.png)
![image](https://user-images.githubusercontent.com/5966955/30121306-9e06752a-932b-11e7-9ad7-8aab5e7b1d55.png)

**Comment by jaydiablo** [comment]
What is the useragent of the device?

You can copy/paste the value from the text input on this page: http://browscap.org/ua-lookup

There was a change made recently that should flag devices like this as Tablet rather than Phone (depending on the UA), but this isn't released yet (should be in the next version of browscap).

**Comment by LuisRamBar** [comment]
The user agent is:
Mozilla/5.0 (Linux; Android 6.0; Aquaris M10 Build/MRA58K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.124 Safari/537.36

The result of the copy/paste is:
ismobiledevice => true
istablet => false

**Comment by jaydiablo** [comment]
Thanks!

This is how that UA parses against `dev-master` using the Lite file (which will be released as version 6025):

```json
{
    "browser_name_regex": "\/^mozilla\\\/5\\.0 \\(.*linux.*android.*\\) applewebkit.* \\(.*khtml.*like.*gecko.*\\) chrome\\\/53\\.0.*safari\\\/.*$\/",
    "browser_name_pattern": "mozilla\/5.0 (*linux*android*) applewebkit* (*khtml*like*gecko*) chrome\/53.0*safari\/*",
    "parent": "Chrome 53.0 for Android",
    "comment": "Chrome 53.0",
    "browser": "Chrome",
    "browser_type": "unknown",
    "browser_bits": "0",
    "browser_maker": "unknown",
    "browser_modus": "unknown",
    "version": "53.0",
    "majorver": "0",
    "minorver": "0",
    "platform": "Android",
    "platform_version": "unknown",
    "platform_description": "unknown",
    "platform_bits": "0",
    "platform_maker": "unknown",
    "alpha": "false",
    "beta": "false",
    "win16": "false",
    "win32": "false",
    "win64": "false",
    "frames": "false",
    "iframes": "false",
    "tables": "false",
    "cookies": "false",
    "backgroundsounds": "false",
    "javascript": "false",
    "vbscript": "false",
    "javaapplets": "false",
    "activexcontrols": "false",
    "ismobiledevice": true,
    "istablet": true,
    "issyndicationreader": "false",
    "crawler": "false",
    "isfake": "false",
    "isanonymized": "false",
    "ismodified": "false",
    "cssversion": "0",
    "aolversion": "0",
    "device_name": "unknown",
    "device_maker": "unknown",
    "device_type": "Tablet",
    "device_pointing_method": "unknown",
    "device_code_name": "unknown",
    "device_brand_name": "unknown",
    "renderingengine_name": "unknown",
    "renderingengine_version": "unknown",
    "renderingengine_description": "unknown",
    "renderingengine_maker": "unknown"
}
```

As you can see, it's detected as a Tablet.

We can add the device to the data files, but that won't affect the Lite file.

**Comment by LuisRamBar** [comment]
I'm sorry, I didn't catch the last sentence.

> We can add the device to the data files, but that won't affect the Lite file.


Anyway, if I haven't misunderstood, in the next version (_which will be released when?_) this point will be corrected, won't it?

Thank you again!

**Comment by jaydiablo** [comment]
Well, device information for most devices is typically only available when you use the Full file, meaning, browscap will not only return if it's a tablet or not, but will tell you the device name and manufacturer. In order for this to happen, we have to add the device to the various browsers for the platforms the device is available on.

This particular device IS in the browscap data files, but not on Android 6.0 (yet).  We can correct this, but it's not going to help your particular use case since you're using the Lite file.

And you are correct, the next release of the browscap file (which will be 6025) will have the change in it that better separates the detection of phones and tablets, especially for the Standard and Lite files that don't have the detailed device information.

6024 was released about a month ago (August 7th), usually the releases are a month or two apart, depending on how many changes have happened since the last release, but no guarantees.

**Comment by mimmi20** [comment]
@jaydiablo Is this issue solved by PR #1574?

**Comment by jaydiablo** [comment]
@mimmi20 It was actually solved by #1548 since @LuisRamBar is using the Lite file.  I just took the opportunity to add the device where seen (in #1574).

**Comment by mimmi20** [comment]
@jaydiablo Can we close this ticket then?

**Comment by jaydiablo** [comment]
@mimmi20 Yes, I think so.
