### ISSUE TITLE
iOS 11 CFNetwork/Darwin detection

### ISSUE THREAD

**Issue by mimmi20** [browscap/browscap#1633]
see ua-parser/uap-core#278 for more details.

**Comment by jaydiablo** [comment]
Thoughts on making these CFNetwork patterns a platform pattern?  Can still be iOS/OSX after parsing but would be labeled as `CFNetwork_iOS_8_0` for example.  Here's how a collection of these may look in the resource files:

Old:
```json
        {
          "match": "Mail/* CFNetwork/758*",
          "platforms": [
            "iOS_A_9_0"
          ]
        },
        {
          "match": "Mail/* CFNetwork/808*",
          "platforms": [
            "iOS_A_10_0"
          ]
        },
        {
          "match": "Mail/* CFNetwork/887*",
          "platforms": [
            "iOS_A_11_0"
          ]
        },
        {
          "match": "Mail/* CFNetwork/*",
          "platforms": [
            "iOS"
          ]
        }
```

New:
```json
        {
          "match": "Mail/* #PLATFORM#",
          "platforms": [
            "CFNetwork_iOS_11_0",
            "CFNetwork_iOS_10_0",
            "CFNetwork_iOS_9_0",
            "CFNetwork_iOS"
          ]
        }
```

There may be cases where we'd have to have a `CFNetwork_OSX_10_12` and a `CFNetwork_OSX_10_12_B` since I have seen cases where a single verison of OSX spans two or more CFNetwork version numbers.

There is one other caveat that would have to be dealt with that I've noticed when looking at a list of UAs.  It seems that the CFNetwork version 887 (for iOS 11) is also shared with macOS 10.13 (high sierra), but the macOS version adds `(x86_64)` to the end of the pattern, like so:

> Mail/3445.1.7 CFNetwork/887 Darwin/17.0.0 (x86_64) 

Here's the iOS version:

>MobileSafari/604.1 CFNetwork/887 Darwin/17.0.0 

For previous CFNetwork versions, this didn't seem to be the case (that iOS and OSX shared the same number), but I do see the `(x86_64)` pattern in most (not all) UAs that get detected as OSX rather than iOS.

This would probably require that a `CFNetwork_OSX_10_13` pattern be defined as `CFNetwork/887*(x86_64)*`, which does work, but does require that the pattern that uses the platform doesn't have any of the `Darwin` string in the pattern.

This won't work with that platform pattern:

`Mail/* #PLATFORM# Darwin/*`

This will:

`Mail/* #PLATFORM#`

I'm not seeing the `Darwin` token used in these patterns at all, so probably not a big deal, just wanted to bring it up.

**Comment by jaydiablo** [comment]
We could make these `iOS` and `OSX` variants as well, rather than `CFNetwork`, so something like:

`iOS_CFNetwork_8_0` and `OSX_CFNetwork_10_12`

**Comment by mimmi20** [comment]
There may be multiple CFNetwork versions for a single iOS/macOS version, because we dont detect micro versions.
