### ISSUE TITLE
Netscape

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1648]
While in issue-492-BU this one is

<pre>
Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.4) Gecko/20030619 Netscape/7.1 (ax)
</pre>

this one isn't :
<pre>
Mozilla/5.0 (Windows; U; Windows NT 6.2; fr-FR; rv:1.4) Gecko/20030624 Netscape/7.1 (ax)
</pre>

On the other side, those are categorized as Netscape version 7.2
<pre>
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.7.2) Gecko/20040804 Netscape/7.2 (ax)
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.7.2) Gecko/20040804 Netscape/7.2 (ax)
</pre>

**Comment by jaydiablo** [comment]
The reason the second UA doesn't parse is because Windows 8 isn't defined as a platform in the Netscape 7.x file.

Netscape 7.1 was released on June 30, 2003 (https://en.wikipedia.org/wiki/Netscape_7#Release_history) and Windows 8 was released on August 1, 2012 (https://en.wikipedia.org/wiki/Windows_8#Release).  I think it's unlikely that Netscape 7.1 even runs on Windows 8, but perhaps it's possible (I'm certain it's not supported ;) ).

We could maybe add a generic file for Netscape that has a generic "Windows" platform defined, just to pick up any of these. I'm not sure it's worth adding Windows 8 to the Netscape 7.x file though.
