### ISSUE TITLE
PlayStation Device Type

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1652]
Why is thi UA's device type is Console as the Browser is "Silk"
<pre>
Mozilla/5.0 (PlayStation Vita 3.65) AppleWebKit/537.73 (KHTML, like Gecko) Silk/3.2
</pre>
When those are TV Device  with a browser which is "Playstation Browser"
<pre>
Mozilla/5.0 (PLAYSTATION 3 4.81) AppleWebKit/531.22.8 (KHTML, like Gecko)
Mozilla/5.0 (PlayStation 4 4.73) AppleWebKit/601.2 (KHTML, like Gecko)
Mozilla/5.0 (PlayStation 4 5.01) AppleWebKit/601.2 (KHTML, like Gecko)
Mozilla/5.0 (PlayStation 4 5.00) AppleWebKit/601.2 (KHTML, like Gecko)
</pre>
What is the difference ?

**Comment by jaydiablo** [comment]
As discussed some here: https://github.com/browscap/browscap/issues/1271#issuecomment-285468130

A "Console" is a device that is self-contained, doesn't require a television to function, which will be the portable game systems, like the Vita, PSP, 3DS, Switch.

A TV Device requires to be connected to a television to function, which will be PS3, PS4, Xbox, Wii/WiiU.

As for the browser difference, we should probably change the Vita's browser from Silk to "Playstation Browser" as well, since it's not really Silk (but may extend on the Silk browser).

https://en.wikipedia.org/wiki/PlayStation_Vita_system_software#Internet_features
http://console.maban.co.uk/device/psvita/

It sounds like it's NetFront based, not sure why Silk appears in the UA, I'll dig some more.

**Comment by mmorel-35** [comment]
Thank you for the clarification.

**Comment by mimmi20** [comment]
I found this a moment ago: https://51degrees.com/blog/sony-ps-vita-browser-detection
