### ISSUE TITLE
Suggestion : Version handling

### ISSUE THREAD

**Issue by mmorel-35** [browscap/browscap#1687]
Could the version be handled at the level of the child with a list as it is today at the main level?

**Comment by mimmi20** [comment]
@mmorel-35 What would be the bennefit? 

The main browsers/apps have a lot of children. Handling the versions a level of the child, would require more work to keep the versions in sync.

**Comment by mmorel-35** [comment]
My point is how can we have the generic browser and the versioned browser in the same file so that we avoid creating too many files .
The other point is that each pattern doesn't necessarily use all the versions of the browser, so it requires the creation of another file.

The final goal is to reduce the number of json files .

**Comment by jaydiablo** [comment]
The `versions` property could be moved to the `userAgent` rather than the `division`, which would allow reducing the files, but I'm not sure that reducing the files is necessarily a good thing in this case.

Right now, if I need to look at the patterns for Chrome 62 because there's some UA that isn't detecting properly, I can open the `chrome-50-on.json` file and don't have to scroll a bunch to find the section I'm looking for.

That said, if the versions lived on the useragent, I wouldn't have had to split Chrome into different groups (android, ios, desktop), but we'd still want separate `userAgent` groupings for each of those, as the version array would be different for each one.  This could result in one giant `chrome.json` file, but I think the file would be quite large, and would require a lot of scrolling to find the `userAgent` section you want to work in.

I don't think there's a lot of harm in having a lot of JSON files if they're well organized and named appropriately. The biggest issue is duplicating properties across the files, and if one of these needs to change for the entire browser, then we'd have to edit all of the useragent files affected.  I think #1681 helps reduce the amount of this though, by moving these properties to the engine. @mimmi20 was also planning on making a `browser` object that would further remove some of these properties from the pattern files (discussed here https://github.com/browscap/browscap/issues/1433#issuecomment-306601290).

**Comment by mmorel-35** [comment]
Chrome is a huge one but for small one which doesn't evolve so fast put the version would be a good idea.

**Comment by mimmi20** [comment]
I dont like the idea that `userAgent`sections could have different versions in one file. I prefer to have separate files for this case.

In general I dont like the idea that we handle big files different than small files.
I the end all files need to be parsed, merged to an huge amount of data, filtered and printed into different files. This process is already complex and would not increase the complexity.
