### ISSUE TITLE
Mobile browsers rethink

### ISSUE THREAD

**Issue by negram** [browscap/browscap#1737]
Hi guys,

Now, when I add new device, it takes about 1 hour of time:
- add new device
- add device code into all browsers I found in logs (Chrome, Android Webview, UCBrowser - two options, Opera Mobile, Yandex Browser, Instagram app, Facebook app and so on)
- add tests

The thing is section for each browser look exactly the same.And (!) still, I don't add all possible variants, as it takes too much time :( .

Basically, it will lead us to the situation when all mobile browser JSON-s will look identically in the future.

I'm pretty sure that this work could be done differently:

we can link browsers and device for App.

I.e. add to device and browser section "platforms". And in the case browser and section have the same platforms, automatically generate all patterns.

For example, how it could be:
devices/samsung.json
```
"Samsung SM-J510FN": {
        "standard": false,
        "properties": {
            "Device_Type": "Mobile Phone",
            "Device_Code_Name": "SM-J510FN",
            "Device_Name": "Galaxy J5 (2016)",
            "Device_Maker": "Samsung",
            "Device_Brand_Name": "Samsung",
            "Device_Pointing_Method": "touchscreen",
            "isMobileDevice": "true",
            "isTablet": "false"
        },
        "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0"
          ]
    },
```

user-agents/browsers/seznam-browser/seznam-browser-android.json
```
  "division": "Seznam Browser #MAJORVER#.#MINORVER# for Android",
  "versions": ["5.1", "5.0", "4.2", "4.1", 4, "3.2"],
  "sortIndex": 1018,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Seznam Browser #MAJORVER#.#MINORVER# for Android",
      "engine": "Blink",
      "device": "general Tablet",
      "platform": "Android",
      "properties": {
...
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) AppleWebKit* (*khtml*like*gecko*) Version/* Chrome/* Safari/* SznProhlizec/#MAJORVER#.#MINORVER#.*",
          "platforms": [
            "Android_7_0", "Android_6_0",, "Android_4_4" 
          ]
        },
{
          "match": "Mozilla/5.0 (#PLATFORM#) AppleWebKit* (*khtml*like*gecko*) Version/* Chrome/* Mobile Safari/* SznProhlizec/#MAJORVER#.#MINORVER#.*",
          "device": "general Mobile Phone (Touch)",
          "platforms": [
            "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4",
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) AppleWebKit* (*khtml*like*gecko*) Version/* Chrome/* Safari/* SznProhlizec/#MAJORVER#.#MINORVER#.*",
          "device": "general Tablet",
          "platforms": [
            "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4",
            "Android"
          ]
        }
...
```

What do you think?

**Comment by mimmi20** [comment]
If I understand right, you want to change the following:

- Each device may have the property `platforms`. This property is optional.
- The useragent may not have a `devices` property, when it has the `###DEVICE###` placeholder.
- If the useragent does not have a devices property, all for each platform all devices (who have this platform) are added.

This would require to add a `match` keyword for the affected devices. For the device in your sample this keyword would get the value `SM-J510FN`.

**Comment by negram** [comment]
Yeah, you're absolutely right

**Comment by jaydiablo** [comment]
I've considered some variation of this for a while now, but there are a few things to consider:

1) If the match is defined on the device, there needs to be a way to support multiple matches, as there are cases in our resources where a single device may have different (valid) matches. I do my best to synchronize this across all browsers/apps (especially on new ones that I add), but I'm positive this isn't the case at the moment.  Some may be "fixable" after some analysis and comparison is done.

2) That said, there may be cases where the same device does have a different match for a different browser/app (for some reason it reports itself differently in a different user agent string). Is there a way with this setup that we could specify which "match" should be used in one browser but not another?  One way could be to define the other match as a different device entirely, but if we're auto-including all devices of the matching platform, we'd need a way to say "only include these devices" or "don't include these devices" to support this.  I'm not **100%** sure that this is currently happening in our files (and is valid) but something to consider.

3) There have been cases where the same "match"/platform has been used for different devices, but I think this is usually a mistake and needs to be corrected. The system would have to be able to detect this at build time though, as it shouldn't be allowed in this type of setup.

4) If we include all devices, on all their supported platforms, on all browsers/apps that have those platforms defined, we could be talking about quite a large increase in the output files (both in size of files and in number of patterns) which could have a negative impact on parsing speed, bandwidth used, disk space consumed, etc...  If such an approach is taken, it may be necessary to further split the browscap files up to provide a "full-devices" file or something like that.

There are certainly a lot of good things with an approach like this though, that would solve a number of problems that I run into regularly (aside from the maintenance aspect that you bring up).

1) This would potentially eliminate a lot of mis-detections that happen when Chrome/Android/Android Webview have a device defined but Opera/Puffin/Maxthon/etc... don't have that same device defined yet.  Since the browscap-php, crossjoin and native get_browser parsers use the length of the pattern as the priority, a long Chrome/Android/Android Webview pattern (due to the device being present) will have more priority than the device-less pattern of these other browsers (even though their "base" is longer).

2) It would be really nice to be able to define, on the device, what platforms it supports.  The device inheritance idea mentioned in #1685 would help with some of the duplication here (for example, there are many Samsung devices that are just regional differences from eachother, and typically support the same versions of Android).

A sort of hybrid approach that we could explore that wouldn't cause the output files to balloon out of control, but still take advantage of defining the platforms on the devices, is a way to define the devices, with or without matches I suppose on a child, and just include all Android versions in the platform list, for example.  If the device has a platform array defined, and matches one of the defined platforms in the UA, it gets included, otherwise it is ignored.

So, perhaps the syntax would be very similar to what we have now, but we wouldn't have to duplicate the children for each platform/device grouping.

For example, here's the seznam android file you use above with these changes in place:

```json
{
          "match": "Mozilla/5.0 (#PLATFORM##DEVICE# Build/*) AppleWebKit* (*khtml*like*gecko*) Version/* Chrome/* Safari/* SznProhlizec/#MAJORVER#.#MINORVER#.*",
          "devices": {
            "ALE-L21": "Huawei ALE-L21",
            "SM-G935F": "Samsung SM-G935F",
            "SM-J510FN": "Samsung SM-J510FN",
            "Vodafone Smart Tab 4G": "Vodafone Smart Tab 4G"
          },
          "platforms": [
            "Android_7_1", "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0"
            "Android_4_4"
          ]
        },
```

We're assuming here that those 4 devices have a `platforms` property defined, and only list the `Android_*` platforms that they each support.  This would result in basically the same output as the current file, we just don't need the duplicate children in order to define what version of android each device supports (this is done on the device).

This doesn't give us the "mis-detection" benefit that I mention above, since we wouldn't be adding new devices to existing browsers/apps at all (maybe only a few here and there since the device might have more versions of android listed than all UAs that the device appears in do), but it would reduce some of the maintenance that we do when adding new devices across multiple browsers/platforms, and give us the advantage of having the supported platforms defined at the device level.

Another thing that an approach like this would affect is the coverage reporting, so we'd want to be sure that any changes made keep that in mind (it may be important to add the devices with a "platforms" property to the coverage report perhaps).

**Comment by negram** [comment]
@jaydiablo,

1. I rather agree, it should be fixable. I mean, this idea can be a starting point - we can start implementing it for devices which report identically across different UAs and then decide what we can do with the rest
2. I'm pretty sure it won't be a problem to add such feature - "include only these devices into this match". As well as I think this feature will not be required most of the times.
3. Hm. Tricky question. Unfortunately I can not imagine the case so far. Probably, you can find some examples?
4. Completeness is a very critical thing for us at this point. We found that Device is not detected for a wide range of cases. And in most cases the device exists in the database but added for one specific browser (sometimes even not most popular one) and that's it. This is very disappointing.

Even the hybrid solution you suggested would be much better than we have now.
