### ISSUE TITLE
Logic of adding new devices

### ISSUE THREAD

**Issue by negram** [browscap/browscap#1741]
Hi again :), 
I noticed that entries I added recently were added not quite correctly: https://github.com/browscap/browscap/pull/1739

So, I'm wondering what's the logic of adding new devices? 
For example, I have bunch of UAs with device SM-J320FN on Android 5.1.1 only and two UAs with SM-J320F, which is almost never used.
Examples (first number is number of occurrencies):

```
17877 Mozilla/5.0 (Linux; Android 5.1.1; SM-J320FN Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36
6248 Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J320FN Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Mobile Safari/537.36
3294 Mozilla/5.0 (Linux; Android 5.1.1; SM-J320FN Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36
2996 Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG SM-J320FN Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/3.5 Chrome/38.0.2125.102 Mobile Safari/537.36
2026 Mozilla/5.0 (Linux; Android 5.1.1; SM-J320FN Build/LMY47V) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36
...
```
```
   4 Mozilla/5.0 (Linux; U; Android 4.4.4; ru-ru; SM-J320F Build/KTU84P) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
   3 Mozilla/5.0 (Linux; Android 7.1.2; SM-J320FN Build/NJH47F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36
```

The question is - how would I add them?

**Comment by jaydiablo** [comment]
@negram They were added fine, I just like to keep things grouped so that it's easier to add new devices in the future (as best as we can with the way the files are built currently).  I would have commented on the PR before merging, but I didn't have time to get to them before @mimmi20 looked them over.  I think in the one PR I commented on, I missed a change that I ended up tweaking in #1739.

Generally, I try to keep the most recent version of a platform at the top of the list, this applies to the groups of UAs (that we see with Android devices) but also with the platforms themselves in the `platforms` array.

So if I had a couple of groups of devices with the same `match` (I try to keep the matches grouped with like matches also) that were these platform groups:

* Android_8_0, Android_7_0
* Android_7_0, Android_6_0
* Android_8_0
* Android_8_1, Android_7_1
* Android_8_0, Android_7_0, Android_6_0

I would usually sort them like so:

* Android_8_1, Android_7_1 (highest version in group is higher than highest version in other groups)
* Android_8_0 (lowest version is higher than lowest version in groups with Android_8_0 as the highest version)
* Android_8_0, Android_7_0
* Android_8_0, Android_7_0, Android_6_0
* Android_7_0, Android_6_0

This is mostly just for organization purposes. The `browscap-php` parser doesn't really care what order they're placed in. There might be small savings by having the more recent versions higher in the file when parsing UAs that also are from more recent versions (the parser has less version comparisons to make when it finds a potential match), but there would probably be a small penalty when looking at older traffic.

As for grouping the UAs, I try to make it so that there is only one "child" for a given match + platform list.  Again, this is mainly for helping us maintain the files, as it doesn't really change the output when the JSON files are processed and built into the resulting XML/JSON/INI/CSV files.

There was a case in one of your PRs where the device you added was defined on two versions of Android, let's say it was `Android_7_0, Android_6_0`. The file it was added to already had a child group defined with just those two platforms, and it had the same `match` as the one you added, so I just removed the extra child and added the device to the existing child that was earlier in the file.  I do have a quick and dirty script that checks for this sort of thing, maybe it's something we can consider adding to a CLI script that we can run, providing some "suggestions" of how to better organize the files or something.

As for the strategy for adding devices, I don't think there is a hard rule here. I usually try to research the device to the best of my ability, and only add platforms for the device for which it is known to support (I then usually add it to all browsers/apps that I have UAs for).

For example, the "SM-J320F(N)" device appears to only support Android 5.1, 6.0, 7.1 officially (I like gsmarena for this, but there are other sources out there as well, I try to look around some, and also see how the UAs that I have compare to what these sites say):

https://www.gsmarena.com/samsung_galaxy_j3_(2016)-7760.php

That one you see that is Android 4.4 is probably spoofed (IMO, though it could be a rooted device with custom android version, like Cyanogen mod or similar, though it seems odd that somebody would downgrade, but certainly not impossible). So if it were me adding that device, I wouldn't add `Android_4_4` at all.  The main reason for this is because of the fourth bullet point I mention in #1737, which is the increase in number of patterns and size of the output files.  

Should 7.1 (and 6.0 for that matter) be added?  I think that's subjective. I just did a search for UAs with that device identified in our logs, and every single one of them came back with Android 5.1. I'd say that just 5.1 is probably a good balance in this case (based on the values from your example and from our logs).  Good enough to cover 99.98% of UAs (based on just our samples of course)?

I think I've mentioned this in other issues, but it's a bit more expensive to add platforms/devices to a browser/app in `browscap` than it is in most other UA parsers that I've looked at (not just in the work to add to the JSON files, but also in the cost to the parser in terms of performance and other considerations).  We could have a single child in each browser/app that has all of the Android versions that browser/app supports, then we could have every android device in that child (which would make a pattern for every device multiplied by every platform listed), but a lot of those patterns are unnecessary (would we ever see Android 4.0 on a Pixel 2? or Android 8.0 on a Galaxy S?), so just adds bloat to the browscap files.

While this limitation requires more work, and reduces the number of possible UAs that the library can detect device information for, it can be useful for pointing out UAs that are obviously spoofed (it won't have device information for a UA that claims it's Android 4.0 on a Pixel 2).

So really it's all a trade-off between adding every possible device/platform and keeping the file size reasonable.  I've tried to help out in that area as much as I can, by adding a lot of coverage where possible which reveals a lot of the platforms/devices which are defined in browscap but that don't really hit any real-world useragents. 

Sorry for the long-winded response, hopefully there's some insight here.
