### ISSUE TITLE
Electron browser has incorrect version

### ISSUE THREAD

**Issue by hadoopbob** [browscap/browscap#1803]
given the user agent string
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Blah(Dev)/0.7.1 Chrome/59.0.3071.115 Electron/1.8.1 Safari/537.36

browser: Electron
browserMajorVersion: 0
deviceType: Desktop
platform: Linux

the version should be 1.8.1

**Comment by jaydiablo** [comment]
browscap currently does not capture the version of the Electron app. This is done typically for lesser-used browsers to reduce the amount of maintenance and the size of the browscap files. So this is expected in this case.

Do you require version information for this app?

**Comment by hadoopbob** [comment]
@jaydiablo  it would be really nice, we have been seeing it more and more lately

**Comment by jaydiablo** [comment]
Here are some unique versions I found in our logs since January of 2017:


useragent | electron_version
-- | --
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat+/1.3.1 Chrome/47.0.2526.110 Electron/0.36.10 Safari/537.36 | 0.36.10
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) PlutoTV/0.2.0 Chrome/49.0.2623.75 Electron/0.37.2 Safari/537.36 | 0.37.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) HyperTerm/0.7.1 Chrome/51.0.2704.106 Electron/1.2.8 Safari/537.36 | 1.2.8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Franz/4.0.4 Chrome/52.0.2743.82 Electron/1.3.1 Safari/537.36 | 1.3.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) designstory/1.0.0 Chrome/53.0.2785.143 Electron/1.4.11 Safari/537.36 | 1.4.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) WhatsApp/0.2.5093 Chrome/53.0.2785.143 Electron/1.4.12 Safari/537.36 | 1.4.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) PlutoTV/0.4.2 Chrome/53.0.2785.143 Electron/1.4.14 Safari/537.36 | 1.4.14
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat+/2.4.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36 | 1.4.15
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) angular-template/1.2.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36 | 1.4.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Raindrop.io/2.0.68 Chrome/53.0.2785.113 Electron/1.4.2 Safari/537.36 | 1.4.2
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) electron/1.0.0 Chrome/53.0.2785.113 Electron/1.4.3 Safari/537.36 | 1.4.3
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) review-tool/2.3.1 Chrome/56.0.2924.87 Electron/1.6.10 Safari/537.36 | 1.6.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) AIRSSampleResumes/1.0.1 Chrome/56.0.2924.87 Electron/1.6.11 Safari/537.36 | 1.6.11
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) DownloadFreeGamesNotifier/1.0.66 Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36 | 1.6.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Front/3.3.9 Chrome/56.0.2924.87 Electron/1.6.2 Safari/537.36 front-desktop | 1.6.2
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/56.0.2924.87 Electron/1.6.4 Safari/537.36 | 1.6.4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Rocket.Chat+/2.8.0 Chrome/56.0.2924.87 Electron/1.6.6 Safari/537.36 | 1.6.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Front/3.8.3 Chrome/58.0.3029.110 Electron/1.7.3 Safari/537.36 front-desktop | 1.7.3
Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Min/1.6.0 Chrome/58.0.3029.110 Electron/1.7.4 Safari/537.36 | 1.7.4
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) electron-quick-start/1.0.0 Chrome/58.0.3029.110 Electron/1.7.6 Safari/537.36 | 1.7.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Franz/5.0.0-beta.14 Chrome/58.0.3029.110 Electron/1.7.9 Safari/537.36 | 1.7.9

**Comment by hadoopbob** [comment]
@mimmi20 @jaydiablo  thanks!

**Comment by hadoopbob** [comment]
@jaydiablo  thanks for all of your hard work, it is very much appreciated!  just wondering when you folks where planning on doing the next release?

**Comment by jaydiablo** [comment]
I'd imagine probably soon, I think we need to clear out the existing PRs that need to be merged, and then as soon as @asgrim has time to put together a new release.
