### ISSUE TITLE
User Agent Lookup for Pixel 2 XL User agent (Chrome v. 66+) issue

### ISSUE THREAD

**Issue by itsvigun** [browscap/browscap#1862]
Mozilla/5.0 (Linux; Android 8.0.0; Pixel 2 XL Build/OPD1.170816.004) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Mobile Safari/537.36

incorrect stats (screen from https://browscap.org/ua-lookup):
http://prntscr.com/jcqm9c

for older Chrome version all is good, for example:
Mozilla/5.0 (Linux; Android 8.0.0; Pixel 2 XL Build/OPD1.170816.004) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3359.139 Mobile Safari/537.36

correct stats:
http://prntscr.com/jcqmw5

**Comment by mestrega** [comment]
I believe this is an issue that spans across all Chrome 66.x versions. 66 was released a month after the last Browscap Release. My Desktop Chrome returns no Version for 66+:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by jaydiablo** [comment]
Yes, Chrome 66 was added in this commit: https://github.com/browscap/browscap/commit/2f9466bda2a84a5ca5ae330ba6df923041092b11#diff-05c494b5188a12170327619fb9f47d8c

But there hasn't been a release of the files since March 3rd.

@asgrim, we're probably due for a new release, can you make some time to cut a release?

**Comment by Cnwangli** [comment]
Hi , Is there a plan to release a new browscap that contains Chrome V66?

Thanks!

**Comment by asgrim** [comment]
This is working as of today - 6.0.29 is on the site, thanks for the patience in waiting for the update :+1:
