### ISSUE TITLE
Add support for native mobile application UA Strings

### ISSUE THREAD

**Issue by varundhall** [browscap/browscap#1920]
Currently there is no support for parsing native mobile application UserAgent strings, they look similar to `Shopkeep-Pocket/4.4.0.389 (Android/7.0 LGE LG-H820)`

There should be a rule in the browscap which can detect and list out the key details from such UserAgent strings.

I've already discussed this on IRC but haven't received any updates from your team.

**Comment by mimmi20** [comment]
@varundhall Do you have any information about the used app? Do you have more useragents like this?

**Comment by varundhall** [comment]
@mimmi20 yes its the [ShopKeep](https://www.shopkeep.com/) app

There are couple of more such UA strings
```
Shopkeep-Pocket/4.4.0.389 (Android/7.0 samsung SM-N920P)
Shopkeep-Pocket/4.4.0.389 (iOS/10.3.3 Apple iPhone 6s) 
Shopkeep-Pocket/4.4.0.389 (iOS/11.1.2 Apple iPhone X)
Shopkeep-Pocket/4.4.0.389 (Android/7.1.1 motorola XT1650)
Shopkeep-Pocket/4.4.0.389 (Android/8.1.0 Google Pixel)
Shopkeep-Pocket/4.4.0.389 (Android/6.0.1 motorola Moto G Play)
```

**Comment by varundhall** [comment]
@mimmi20 basically I expect some rules in Browscap for native applications

**Comment by jaydiablo** [comment]
The challenge in browscap is that there is no concept of capturing groups due to the nature of the browscap file formats (while the patterns contained in the browscap files are regular expression friendly, they aren't actually regular expressions).

So, we could add patterns that will capture this `Shopkeep-Pocket` application, and will mark it as such when parsed (with the appropriate Android version), that would only add detection for the Shopkeep-Pocket app.

It's possible to add a generic pattern that would parse these as something generic, like "Native Android Application" or something like that, which would at least prevent them from being marked as `Default Browser` by browscap, but won't allow you to get any other information about the UA (other than Android version).

We can add patterns for the specific applications, but they'd have to be reported/added manually for each app.

That said, one could possibly write an extension to browscap in whatever language they're using that looks for that "Native Android Application" browser returned from browscap (if such a thing were to be added) and then do their own capturing group on the application + version if it was really important to have that application name/version extracted from these types of UAs.
