### ISSUE TITLE
Ipad pro 2019 is detected as desktop instead of tablet

### ISSUE THREAD

**Issue by germainppaimparay** [browscap/browscap#2282]
Dear browscap team, 

User agent of my ipad pro is : 

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15

So browscap detected as desktop instead of an tablet.

Best regards,

More information : 
https://www.scientiamobile.com/detect-ipados-13/

**Comment by asgrim** [comment]
Since we only analyse user agents, this is impossible, since the desktop UA is passed.

**Comment by GaryKeith** [comment]
﻿Hi James,

I’m happy you’re still keeping the project going.

I recently started receiving a flood of daily emails about various issues and commits. I tried unsubscribing from what appears to be two lists to no avail. I’m not even sure why I’m receiving them because I long ago deleted the email address and GItHub accounts I used for BrowsCap. Can you please find what’s triggering these emails and delete them for me?

Thanks,
~gary.

**Comment by mimmi20** [comment]
see here: #2232

**Comment by mimmi20** [comment]
@GaryKeith You still have an Github Account

**Comment by asgrim** [comment]
> I recently started receiving a flood of daily emails about various issues and commits. I tried unsubscribing from what appears to be two lists to no avail. I’m not even sure why I’m receiving them because I long ago deleted the email address and GItHub accounts I used for BrowsCap. Can you please find what’s triggering these emails and delete them for me?

I've verified you're not on the browscap members list. Check the notifications settings you have @GaryKeith, I can't really help otherwise...
