### ISSUE TITLE
OS detection from Edge UA string is deprecated

### ISSUE THREAD

**Issue by WilliamStam** [browscap/browscap#2706]
THE BROWSCAP CORRECTLY DETECTS THE BROWSER FROM THE STRING. but i got totally stumped on the OS part. Im more adding this here for any future searchers since i didn't see any in the tracker for this issue. 

the issue has to do with the OS detection part. chrome and its kin have started depreciating the OS part in the UA and instead relying on "Client Hints".

im on win11 but the user agents for chrome and its derivatives have frozen the os to win10. 

https://docs.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11

# User agent(s)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.27

# Browscap version tested on

6001001 https://browscap.org/stream?q=PHP_BrowsCapINI

thanks team for all your work on this project! 

(and in a bit of a sad turn of events... seems with this change server side knowing what browser is going to be phased out more and more i guess)

**Comment by asgrim** [comment]
> seems with this change server side knowing what browser is going to be phased out more and more i guess

I've been advocating for not doing UA sniffing for a long time now, we only maintain this project for legacy things, and anything new, I would encourage against using UA sniffing anyway.

At the end of the day, yes, if OS details are removed from (or frozen in) the UA, we can't do much more than what we do. It is what it is, UA sniffing has only ever been a "best guess" approach, because at the end of the day, it relies on a client-provided string which may be inaccurate :)
