### ISSUE TITLE
Our IP is permanently banned

### ISSUE THREAD

**Issue by ktsmokolyuk** [browscap/browscap#2776]
Hi there,

Could you unblock our IP - 54.175.88.73

Issue:
~# /usr/bin/wget -O "lite_php_browscap.ini" "https://browscap.org/stream?q=Lite_PHP_BrowsCapINI"
--2023-01-24 11:48:52--  https://browscap.org/stream?q=Lite_PHP_BrowsCapINI
Resolving browscap.org (browscap.org)... 172.67.153.244, 104.21.12.245, 2606:4700:3032::ac43:99f4, ...
Connecting to browscap.org (browscap.org)|172.67.153.244|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-01-24 11:48:52 ERROR 403: Forbidden.

~# 

We have many servers and each server downloads a new version daily between time UTC 9:00 - 11:00

But it seems that this is too often and our IP was blocked

We updated cron to download once a week (Sunday only) between 9:00AM - 1:00PM

Cron:
  - name: 'Install default jobs'
    cron:
      name: "{{ item.name }}"
      minute: "{{ item.minute }}"
      hour: "{{ item.hour }}"
      weekday: "{{ item.weekday }}"
      job: "{{ item.job }}"
    with_items:
            - { name: 'Browscap update', minute: '01', hour: '09', weekday: '0', job: 'sleep $[RANDOM\%14400]m ; /usr/bin/wget -O "/etc/php/lite_php_browscap.ini" "https://browscap.org/stream?q=Lite_PHP_BrowsCapINI"'}

Thanks !

**Comment by asgrim** [comment]
Yes, your IP was banned because you are downloading the file too frequently:

 * You may download 30 files per 1 hour period. If you exceed this you will be temporarily banned for 1 hour.
 * You are allowed up to 5 temporary bans in a 3 day period. If you exceed this, you will be permanently banned.

You do NOT need to download the file every time, you should check the `/version` or `/version-number` endpoint, and compare it against the version you already have.

Additionally, you should avoid downloading from all your servers at the same time. I can see you try to download the files approximately 30 times at the same time.

Please be more considerate in future.
