### ISSUE TITLE
IP Address Permanently Banned

### ISSUE THREAD

**Issue by lytvynskyiATD** [browscap/browscap#3034]
Hello,
Unfortunately, we noticed that were banned. Now we get:
{"response":"Rate limit exceeded for 34.159.1.223. You have been permantly banned for abuse."} in the body response. I think this may have happened after we moved to a new infrastructure and our cronjob was not configured correctly. So please, can you unban us?

**Comment by asgrim** [comment]
> Hello, Unfortunately, we noticed that were banned. Now we get: {"response":"Rate limit exceeded for 34.159.1.223. You have been permantly banned for abuse."} in the body response. I think this may have happened after we moved to a new infrastructure and our cronjob was not configured correctly. So please, can you unban us?

Hi, I did receive your email the other day, and unbanned the IP; however it has been banned again because something from that IP continued to download the file `lite_php_browscapini` too much, with user agent `Fuel PHP framework - Agent class (https://fuelphp.com)`.

It looks like this IP is a Google IP, so unless you have dedicated egress IP, that may be traffic from someone else.

**Comment by lytvynskyiATD** [comment]
Thanks for your answer, i will investigate it

**Comment by asgrim** [comment]
@lytvynskyiATD I have unbanned the IP again.
