### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by dangrossman** [browscap/browscap#600]
Have you ever considered putting this site behind Cloudflare?

Cloudflare is free, acts as a content cache, and gives you unlimited bandwidth.

Would this not reduce the resources needed to host the project to a ~$5/mo VPS? And you'd be able to throw out all the rate limiting code and associated headache of dealing with bans/unbans.

**Comment by asgrim** [comment]
Pretty sure it would violate terms of service:

> Using an account primarily as an online storage space, including the storage or caching of a disproportionate percentage of pictures, movies, audio files, or other non-HTML content, is prohibited. You further agree that if, at CloudFlare's sole discretion, you are deemed to have violated this section, or if CloudFlare, in its sole discretion, deems it necessary due to excessive burden or potential adverse impact on CloudFlare's systems, potential adverse impact on other users, server processing power, server memory, abuse controls, or other reasons, CloudFlare may suspend or terminate your account without notice to or liability to you.

We get through about 4 TB of bandwidth a month, so they'd almost certainly notice this high usage from just one account. I may enquire to them though.

**Comment by dangrossman** [comment]
I'd suggest asking. I don't think a website like browscap is what that intends to prohibit. 4TB of traffic is not a whole lot for Cloudflare; some of the largest sites on the 'net are behind their CDN, and they've absorbed nearly terabit-per-second DDoS's. At most they might ask you to get on a paid plan, which starts at $20 per month.

**Comment by asgrim** [comment]
I've submitted an enquiry

**Comment by asgrim** [comment]
Well, I've put it on CloudFlare, we'll see if it makes any difference. Interesting graph here - I turned off the "rate limiting" that we have implemented on the website whilst I was turning CloudFlare on - check out the bandwidth spike - previously we averaged about 15mb/s, we spiked to around 120mb/s (over 5 minute averages):

![screenshot 2015-03-30 at 20 16 05](https://cloud.githubusercontent.com/assets/496145/6904603/e46be606-d719-11e4-80ba-c9438c64cfdc.png)

Hopefully CF will bring down our 15mb/s average, otherwise there's not really much point o_O

**Comment by dangrossman** [comment]
Cloudflare doesn't cache INI files by default, so you'd have to set up a "page rule" telling it to do so (or turn on caching of the whole site), for it to save you bandwidth on the downloads

**Comment by asgrim** [comment]
Hmm - well our internal rate limiting does not work with CF's caching (as CF was caching "rate limit exceeded" for an IP that wasn't mine instead of the files themselves).

I turned off our rate limiting, and put aggressive caching on:

![screenshot 2015-03-30 at 21 19 30](https://cloud.githubusercontent.com/assets/496145/6905849/bd7f5b1e-d722-11e4-890b-0734b3789ac1.png)

but this has resulted in a traffic peak again back up to about 100mb/s

![screenshot 2015-03-30 at 21 22 20](https://cloud.githubusercontent.com/assets/496145/6905863/dfa0115c-d722-11e4-951f-07579041a40e.png)

I'm going to leave it as-is for now but maybe I didn't configure something properly.

**Comment by asgrim** [comment]
Well, even without the aggressive caching enabled, it's made a small dent in the traffic:

![traffic](https://cloud.githubusercontent.com/assets/496145/6913660/a31a9c40-d77a-11e4-813c-25e5f64949d2.png)

Always good! I'll continue to monitor :)

**Comment by dangrossman** [comment]
:+1: 

Perhaps you can turn on the aggressive caching without turning off your rate limiting code by whitelisting Cloudflare's IPs:

https://www.cloudflare.com/ips

**Comment by asgrim** [comment]
The way I understand it, 100% of our traffic now proxies via CF, so all traffic looks like it's coming from CF currently. We read a header that gets sent through from CF which has the original visitor's IP, that's how we do the rate limiting now (see [StreamController.php#L58](https://github.com/browscap/browscap-site/blob/master/src/BrowscapSite/Controller/StreamController.php#L58)). If I understand correctly, that means if we whitelist CF's IP, it would essentially disable all of the rate limiting :/

**Comment by dangrossman** [comment]
With aggressive caching on, theoretically, CF would not proxy anything back to your origin server. It'd respond to requests from end-users directly from its own cache servers. The only requests you would see are cache updates to replace the copies on their servers as they expire (according to your TTL). In theory, again :x

**Comment by asgrim** [comment]
Yeah, that didn't seem to be happening - although maybe I didn't get the rule pattern right or something - the second spike in the graph up there was me trying that. I'll have a bit more of a look into it another time, but it has dramatically reduced our bandwidth usage even on the current settings. Over the last day, we average about 1mbps, which should help a lot (so thanks for suggesting that!). If the bandwidth can be reduced enough, then I should be able to just host it on a single Digital Ocean droplet rather than the beefy Linode we've got at the moment.

**Comment by benjojo** [comment]
Hi! Please raise another ticket though with us and we can take a look at why the bandwidth is spiking (Since we will be able to see in what state your page rules in to ensure that they are right)

**Comment by asgrim** [comment]
https://twitter.com/browscap/status/618670266365923328 - says it all really ;0

**Comment by dangrossman** [comment]
That's great to hear :+1:
