### ISSUE TITLE
Regression between version 6013 and 6014

### ISSUE THREAD

**Issue by wggdeveloper** [browscap/browscap#961]
Using all the UAs from useragentstring.com I compiled a [list](https://github.com/browscap/browscap/files/244120/regression.txt) of 616 (5.72%) strings which was detected in 6013 but not in 6014. The second column contains the matching patterns from 6013.

**Comment by wggdeveloper** [comment]
Here is another [list](https://github.com/browscap/browscap/files/244151/regression.txt) compiled from the tests of ua-parser/uap-core. There could be a couple of specifically crafted test strings, but most of them are real UAs.

**Comment by mimmi20** [comment]
@wggdeveloper These Uas are not detected, because we removed these rules. There were false positives and wrong detected fakes in there.

Your lists are too long and include too much duplicate useragents. Please remove the following from your lists:
- user agents with changes in Gecko release dates only
- user agants with changes in the micro version or alpha/beta flags only
- user agents with changes in the language key only
- user agants with different size of spaces inside only
- every user agent who looks like a fake
- every user agant with not existing versions, Windows NT codes, combinations of browser/os
- additional information like Linux system (e.g. red hat, fedora, debian), other software (mega upload)

For the remaining Uas please add a suggestion what the browser name should be.

**Comment by jaydiablo** [comment]
This is an old issue, but I was curious how the most recent version (dev-master as of this writing) of browscap handles the agents in the first file.  Almost all of them parse as "Default Browser", except this batch:

>Mozilla/5.0 (Macintosh; ; Intel Mac OS X; fr; rv:1.8.1.1) Gecko/20061204 Opera
Mozilla/5.0 (Macintosh; Intel Mac OS X; U; nb; rv:1.7.5) Gecko/20041110
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-au; rv:1.9.0.1) Gecko/2008070206
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.0.1) Gecko/2008070206
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.13; ) Gecko/20101203
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.3) Gecko/20100402 Prism/1.0b4
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.11) Gecko/20071127
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.11) Gecko/20071206
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.13) Gecko/20080313 Firefox
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en; rv:1.8.1.2pre) Gecko/20070223
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; nl-NL; rv:1.8.1.3) Gecko/20080722
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.3a) Gecko/20030101 Phoenix/0.5
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.4a) Gecko/20030401
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.5.1) Gecko/20031120
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.6) Gecko/20040113
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.13) Gecko/20060414
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.2) Gecko/20040803
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.6) Gecko/20050319
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.1.1) Gecko/20061204
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.1a2) Gecko/20060512
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8b) Gecko/20050217
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.9a1) Gecko/20060707 SeaMonkey/1.5a
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; es-ES; rv:1.7.3) Gecko/20040910
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; fr-FR; rv:1.7.11) Gecko/20050727
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; fr; rv:1.7.3) Gecko/20040910
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; rv:1.8.1.16) Gecko/20080702 Firefox
Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US; rv:1.1a) Gecko/20020610
Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US; rv:1.2) Gecko/20021126
Mozilla/5.0 (Macintosh; U; PPC Mac OS X; en-US; rv:1.2b) Gecko/20021016
Mozilla/5.0 (Windows NT 6.2; WOW64; rv:1.8.0.7) Gecko/20110321 MultiZilla/4.33.2.6a SeaMonkey/8.6.55
Mozilla/5.0 (Windows; U; Windows NT 6.0; de; rv:1.9.0.15) Gecko/2009101601 Firefox 2.1 (.NET CLR 3.5.30729)
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-GB; rv:1.9.0.13) Gecko/2009073022 EnigmaFox/3.0.13
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-GB; rv:1.9.0.7) Gecko/2009021910 MEGAUPLOAD 1.0
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.7.13) Gecko/20060414
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1b3) Gecko/20090305
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.3pre) Gecko/20100403 Lorentz/3.6.3plugin2pre (.NET CLR 4.0.20506)
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.3a3pre) Gecko/20100306 Firefox3.6 (.NET CLR 3.5.30729)
Mozilla/5.0 (Windows; U; Windows NT 6.1; it; rv:2.0b4) Gecko/20100818
Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:1.8.0.7) Gecko/20110321 MultiZilla/4.33.2.6a SeaMonkey/8.6.55
Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:2.2) Gecko/20110201
Mozilla/5.0 (Windows; U; Windows NT 6.2; en-US; rv:1.9.1.4) Gecko/20091104 SeaMonkey/2.0
Mozilla/5.0 (Windows; U; Windows NT 6.2; WOW64; rv:1.8.0.7) Gecko/20110321 MultiZilla/4.33.2.6a SeaMonkey/8.6.55

These all detect as "Firefox" version "0" on various platforms.  I feel that some should probably not be Firefox (SeaMonkey, EnigmaFox, MultiZilla, Phoenix (Firefox before it was called Firefox)).  Most of the others don't contain the "Firefox" keyword at all, but there are some generic patterns catching some of those, like this one for "Generic Firefox" on OSX: `mozilla/5.0 (*mac os x*) gecko*/*` or this one for Windows Vista: `mozilla/5.0 (*windows nt 6.0*) gecko*/*` (perhaps these need to be removed like some of the others were?)

As for the rest, a chunk of them look like legit Phoenix UAs (AFAICT), since the Gecko build number seems old enough to be pre-Firefox naming (http://website-archive.mozilla.org/www.mozilla.org/firefox_releasenotes/en-US/firefox/releases/0.5.html):

>Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.3a) Gecko/20021207 Phoenix/0.5
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.2b) Gecko/20021001 Phoenix/0.2
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.2b) Gecko/20021014 Phoenix/0.3
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.2b) Gecko/20021029 Phoenix/0.4
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.3a) Gecko/20021203 Phoenix/0.4
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.3a) Gecko/20021207 Phoenix/0.5
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.3a) Gecko/20030105 Phoenix/0.5
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.4a) Gecko/20030403 Phoenix/0.5
Mozilla/5.0 (Windows; U; Windows NT 5.1; de-DE; rv:1.3a) Gecko/20021207 Phoenix/0.5
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.2b) Gecko/20020923 Phoenix/0.1
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.2b) Gecko/20021014 Phoenix/0.3
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.2b) Gecko/20021029 Phoenix/0.4
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.3a) Gecko/20021207 Phoenix/0.5
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.4a) Gecko/20030411 Phoenix/0.5
Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.2b) Gecko/20021029 Phoenix/0.4
Mozilla/5.0 (Windows; U; WinNT4.0; en-US; rv:1.3a) Gecko/20021207 Phoenix/0.5
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2b) Gecko/20021014 Phoenix/0.3
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.2b) Gecko/20021029 Phoenix/0.4
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.3a) Gecko/20021207 Phoenix/0.5

That's a pretty ancient browser though, so not sure if it's worth adding patterns for.

There are a handful that look like they could be early versions of Firefox, perhaps browscap doesn't have the platform matches for them though (some are unusual platforms, or not typical for the platform they claim they are):

>Mozilla/5.0 (BeOS; U; BeOS BePC; en-US; rv:1.9a1) Gecko/20051002 Firefox/1.6a1
Mozilla/5.0 (Windows 98; U; en; rv:1.8.0) Gecko/20060728 Firefox/1.5.0
Mozilla/5.0 (Windows; U; Win 9x 4.90; en-US; rv:1.6) Gecko/20040206 Firefox/0.8
Mozilla/5.0 (Windows; U; Win 9x 4.90; rv:1.7) Gecko/20040803 Firefox/0.9.3
Mozilla/5.0 (Windows; U; Win98; de-DE; rv:1.7) Gecko/20040803 Firefox/0.9.3
Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.6) Gecko/20040206 Firefox/0.8
Mozilla/5.0 (Windows; U; Win98; rv:1.7.3) Gecko/20040913 Firefox/0.10
Mozilla/5.0 (Windows; U; Win98; rv:1.7.3) Gecko/20041001 Firefox/0.10.1
Mozilla/5.0 (Windows; U; Windows NT5.1; en; rv:1.7.10) Gecko/20050716 Firefox/1.0.5
Mozilla/5.0 (X11; U; Mac OSX; it; rv:1.9.0.7) Gecko/2009030422  Firefox/3.0.7
Mozilla/5.0 (X11; U; NetBSD alpha; en-US; rv:1.8.1.6) Gecko/20080115 Firefox/2.0.0.6
Mozilla/5.0 (X11; U; NetBSD amd64; fr-FR; rv:1.8.0.7) Gecko/20061102 Firefox/1.5.0.7
Mozilla/5.0 (X11; U; NetBSD i386; en-US; rv:1.8) Gecko/20060104 Firefox/1.5
Mozilla/5.0 (X11; U; NetBSD i386; en-US; rv:1.8.0.5) Gecko/20060818 Firefox/1.5.0.5
Mozilla/5.0 (X11; U; NetBSD sparc64; fr-FR; rv:1.8.1.6) Gecko/20070822 Firefox/2.0.0.6
Mozilla/5.0 (ZX-81; U; CP/M86; en-US; rv:1.8.0.1) Gecko/20060111 Firefox/1.5.0.1
Mozilla/6.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:2.0.0.0) Gecko/20061028 Firefox/3.0
Mozilla/6.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.8
Mozilla/6.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.8 (.NET CLR 3.5.30729)
Mozilla/6.0 (Windows; U; Windows NT 7.0; en-US; rv:1.9.0.8) Gecko/2009032609 Firefox/3.0.9 (.NET CLR 3.5.30729)

There are some that look like legit SeaMonkey UAs (I removed a few that had versions of SeaMonkey that don't exist (like 8.x, when [SeaMonkey is only at 2.46](http://www.seamonkey-project.org/releases/)):

>Mozilla/5.0 (BeOS; U; BeOS BePC; en-US; rv:1.9a1) Gecko/20060702 SeaMonkey/1.5a
Mozilla/5.0 (BeOS; U; Haiku BePC; en-US; rv:1.8.1.10pre) Gecko/20080112 SeaMonkey/1.1.7pre
Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.8.0.6) Gecko/20060730 MultiZilla/1.8.2.0i SeaMonkey/1.0.4
Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.8.0.7) Gecko/20060910 MultiZilla/1.8.2.0i SeaMonkey/1.0.5
Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.8.1.3pre) Gecko/20070307 SeaMonkey/1.1.1+
Mozilla/5.0 (OS/2; U; Warp 4.5; en-US; rv:1.9a1) Gecko/20051119 MultiZilla/1.8.1.0s SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.9a1) Gecko/20060206 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a1) Gecko/20060520 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a1) Gecko/20060906 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a2pre) Gecko/20070109 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a2pre) Gecko/20070130 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a3pre) Gecko/20070317 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a4pre) Gecko/20070404 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9a5pre) Gecko/20070527 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; Windows NT 5.1; pl-PL; rv:1.9a1) Gecko/20060812 SeaMonkey/1.5a
Mozilla/5.0 (Windows; U; WinNT3.51; en-US; rv:1.8.1.8) Gecko/20071009 SeaMonkey/1.1.5
Mozilla/5.0 (X11; U; Fedora 12 i686; nb-NO; rv:1.9.1.8) Gecko/20100205 SeaMonkey/2.0.3
Mozilla/5.0 (X11; U; Fedora i686; en-US; rv:1.9.1.19) Gecko/20110429 Fedora/2.0.14-1.fc14 SeaMonkey/2.0.14

Some ["lolifox"](http://lolifox.software.informer.com/) agents (not actively developed anymore, official website is now a parked domain):

>Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070224 lolifox/0.3.2
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070224 lolifox/0.3.2 MEGAUPLOAD 1.0
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070225 lolifox/0.32
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1b1) Gecko/20060713 lolifox/0.2.4
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2) Gecko/20070225 lolifox/0.32
Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.8.1) Gecko/20061127 lolifox/0.3.0
Mozilla/5.0 (X11; U; Linux x86_64; en-US; rv:1.8.1) Gecko/20061127 lolifox/0.3.0

Some [K-Ninja/K-Ninja Samurai](http://kmeleonbrowser.org/forum/read.php?1,38731), also doesn't appear to be maintained, and very old:

>Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.8.0.7) Gecko/20060917 K-Ninja/2.0.4
Mozilla/5.0 (Windows; U; Win98; en-US; rv:1.8.1.4pre) Gecko/20070404 K-Ninja/2.1.3
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.5) Gecko/20060706 K-Ninja/2.0
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.6) Gecko/20060731 K-Ninja/2.0.2
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.0.7) Gecko/20060917 K-Ninja/2.0.4
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1
Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.4pre) Gecko/20070404 K-Ninja/2.1.3

There are a few other various ones, like IceWeasel, Prism, Midori, Charlotte and Thunderbird, but then the rest of them are pretty much all what appears to be an early-ish version of Gecko with no other identifier, across several different platforms.  Some of them do have a linux variant as an identifier after `Gecko/*`, which I assume is because some distributions re-branded the firefox/mozilla browser as their own (Like Debian did with Iceweasel).

So, for example, this one:

>Mozilla/5.0 (Windows; U; Windows NT 5.0; de-AT; rv:1.0.1) Gecko/20020826

Based on the Gecko build number there, this pre-dates Firefox (released in [2004](https://en.wikipedia.org/wiki/Firefox#History)), so if this is a legit UA, what should browscap detect it as?  Mozilla? (I think this applies to the batch that is detected by the "Generic Firefox" pattern as well).  Should browscap be detecting UAs without "Firefox" in them as Firefox?

FWIW, these generic, "Firefox"-less patterns don't appear to be covered by tests:

https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-generic.json#L157
https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-generic.json#L171
https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-generic.json#L185

**Comment by mimmi20** [comment]
For the pattern `mozilla/5.0 (*windows nt 6.0*) gecko*/*` (or its macOS version) exists a test case. Maybe the pattern should be updated.

The ua `Mozilla/5.0 (Windows; U; Windows NT 6.1; rv:1.8.0.7) Gecko/20110321 MultiZilla/4.33.2.6a SeaMonkey/8.6.55` should be detected as `Multizilla`.

For the browsers like lolifox or K-Ninja we could add a generic pattern without version to make sure they are not detected as Firefox.

The Firefox-less Gecko-based Uas should match to Mozilla, but I removed these patterns in version 6014.

**Comment by jaydiablo** [comment]
The only test case I can find that has the `Comment` of `Firefox Generic` is this one:

```
ack "Firefox Generic" ./tests/fixtures/issues/
    tests/fixtures/issues/issue-096.php
    1385:            'Comment' => 'Firefox Generic',
```
https://github.com/browscap/browscap/blob/master/tests/fixtures/issues/issue-096.php#L1382

Which appears to match the coverage report: https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-generic.json#L103 (only green line in the file).

**Comment by mimmi20** [comment]
For this pattern exists also a verioned one: `Mozilla/5.0 (#PLATFORM#) Gecko*/#MAJORVER#.#MINORVER#*`.  Test cases for that are in issue-436 and in issue-618.

**Comment by jaydiablo** [comment]
Ah, I see, covered patterns are here:

https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-5-29.json#L173

https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-5-29.json#L183

https://codecov.io/gh/jaydiablo/browscap/src/4326c5a6437b98b232f9a6eee21f2cc210a3ed4d/resources/user-agents/browsers/firefox/firefox-30-40.json#L187

Perhaps some others.

However, those patterns won't match the ones above that were detected as "Firefox" as the `#MAJORVER#.#MINORVER#` match won't match `Gecko/20020201` and other variations since they're lacking the dot.  Only those un-versioned patterns in the firefox generic file will match those.

Should those patterns remain?

Should patterns like these be detected as firefox?

>Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.11) Gecko/20071127
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en-US; rv:1.8.1.11) Gecko/20071206
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; en; rv:1.8.1.2pre) Gecko/20070223
Mozilla/5.0 (Macintosh; U; Intel Mac OS X; nl-NL; rv:1.8.1.3) Gecko/20080722
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.4a) Gecko/20030401
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.5.1) Gecko/20031120
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.6) Gecko/20040113
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.13) Gecko/20060414
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.2) Gecko/20040803
Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.7.6) Gecko/20050319
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.7.13) Gecko/20060414
Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.9.1b3) Gecko/20090305
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US; rv:1.9.2.3pre) Gecko/20100403 

One of the patterns I linked to above looks like this:

`Mozilla/5.0 (#PLATFORM#rv:#MAJORVER#.#MINORVER#*) Gecko*/`

Which seems like it could be used to match some of these useragents, but the versions don't match up (this pattern is from the file that defines these versions: `[29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5]`).  There is a file that defines the 1.x versions, but it doesn't have any "firefox-less" patterns.

For other parsers that do detect a browser name, it seems they opt for "Mozilla" instead of Firefox. Browscap is the only parser that chooses Firefox for these types of strings (http://useragent.mkf.solutions/?userAgent=Mozilla%2F5.0+%28Macintosh%3B+U%3B+Intel+Mac+OS+X%3B+en-US%3B+rv%3A1.8.1.11%29+Gecko%2F20071206).

For all of the ones that Browscap detects as Firefox, here's how a bunch of other parsers parse the browser name:

```
+---------------------+------------------+------------------+-------------------------+----------------+------------------+----------------+------------------+------------------+------------------+
| browscap-php-3-full | donatj-0         | endorphin-3      | piwik-device-detector-3 | sinergi-6      | ua-parser-php-3  | ua-parser-js-0 | whichbrowser-2   | woothee-php-1    | zsxsoft-php-1    |
+---------------------+------------------+------------------+-------------------------+----------------+------------------+----------------+------------------+------------------+------------------+
| firefox (173)       | [no value] (172) | [no value] (167) | [no value] (144)        | mozilla (146)  | [no value] (152) | mozilla (151)  | [no value] (145) | [no value] (173) | [no value] (129) |
|                     | firefox (1)      | firefox (6)      | seamonkey (15)          | seamonkey (15) | seamonkey (14)   | seamonkey (14) | seamonkey (15)   |                  | seamonkey (11)   |
|                     |                  |                  | firefox (7)             | phoenix (7)    | phoenix (7)      | phoenix (7)    | phoenix (7)      |                  | phoenix (7)      |
|                     |                  |                  | phoenix (7)             | firefox (5)    |                  | khtml (1)      | firefox (6)      |                  | firefox (6)      |
|                     |                  |                  |                         |                |                  |                |                  |                  | kninja (5)       |
|                     |                  |                  |                         |                |                  |                |                  |                  | lolifox (5)      |
|                     |                  |                  |                         |                |                  |                |                  |                  | multizilla (4)   |
|                     |                  |                  |                         |                |                  |                |                  |                  | prism (2)        |
|                     |                  |                  |                         |                |                  |                |                  |                  | kmlite (1)       |
|                     |                  |                  |                         |                |                  |                |                  |                  | vonkeror (1)     |
|                     |                  |                  |                         |                |                  |                |                  |                  | enigmafox (1)    |
|                     |                  |                  |                         |                |                  |                |                  |                  | lorentz (1)      |
+---------------------+------------------+------------------+-------------------------+----------------+------------------+----------------+------------------+------------------+------------------+
```

That's against the following agents:

[firefox-or-not.txt](https://github.com/browscap/browscap/files/856230/firefox-or-not.txt)

**Comment by mimmi20** [comment]
I think we can remove these two pattern.

**Comment by jaydiablo** [comment]
There are a handful of `SeaMonkey/1.5a` UAs in that first list:

>Mozilla/5.0 (Windows; U; Windows NT 5.0; en-US; rv:1.9a1) Gecko/20060206 SeaMonkey/1.5a

According to the SeaMonkey website, 1.5a was never officially released: http://www.seamonkey-project.org/releases/#old_unofficial

I did find a discussion that 1.5a did exist as a testing/nightly build briefly: http://sillydog.org/forum/sea-monkey-1-5-alpha-nightly-buid-for-testing-only-t10182s2399.php

But I assume they decided to bump to 2.0 instead of releasing 1.5.  Should 1.5 be added as a SeaMonkey version even though it was just a nightly build and not officially released?

**Comment by mimmi20** [comment]
I think, we can add this version. This is the same like Firefox 3.7 and 3.8 who are available in our resources.

**Comment by jaydiablo** [comment]
I have a PR coming for this, probably later today, but I wanted to share how the two attached files will parse after my changes:

[issue-961-2-new.csv.zip](https://github.com/browscap/browscap/files/861782/issue-961-2-new.csv.zip)
[issue-961-new.csv.zip](https://github.com/browscap/browscap/files/861781/issue-961-new.csv.zip)

There are still a fair amount of "Default Browser"s in there, but I think that's fine since most look to be fake/malformed for one reason or another (there are probably still some valid agents that aren't being caught as well, but they're mostly odd variants).

**Comment by mimmi20** [comment]
@jaydiablo Could we close this issue?

**Comment by jaydiablo** [comment]
Yeah, I think the valid UAs have been dealt with.
